apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-analytics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-analytics
  template:
    metadata:
      labels:
        app: weather-analytics
    spec:
      containers:
        - name: weather-analytics
          image: 530540751236.dkr.ecr.ap-south-1.amazonaws.com/weather-analytics:1094f903a036a464ff4bcebdd6c0578cc2b41a33
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
